name: Compile and Run Password Generator

on:
  workflow_dispatch: # Enables the interactive run button in the GitHub Web App
    inputs:
      password_length:
        description: 'Enter the number of characters or password length (1-20):'
        required: true
        default: '12'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Compile C++ Program
      working-directory: hash_funcs/strong_password
      run: |
        g++ -std=c++17 -o gp gp.cpp

    - name: Run Executable inside Web App
      working-directory: hash_funcs/strong_password
      run: |
        # Echoes the web UI input value straight into the C++ terminal prompt
        echo "${{ github.event.inputs.password_length }}" | ./gp
